//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isik.SAMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMS_DepartmentProgramRel
    {
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public string DepartmentName { get; set; }
        public string ProgramName { get; set; }
        public Nullable<int> Quota { get; set; }
        public Nullable<int> Duration { get; set; }
        public bool IsThesisIncluded { get; set; }
    
        public virtual SAMS_Department SAMS_Department { get; set; }
        public virtual SAMS_Program SAMS_Program { get; set; }
    }
}
