//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isik.SAMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SAMS_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAMS_Users()
        {
            this.SAMS_StudentApplications = new HashSet<SAMS_StudentApplications>();
            this.SAMS_StudentApplications1 = new HashSet<SAMS_StudentApplications>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedTime { get; set; }
        public Nullable<int> UserType { get; set; }
        [DisplayName("E-Mail")]        
        [Required(ErrorMessage="The Email Field is required")]
        public string Email { get; set; }
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "The Password Field is required")]
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ProgramId { get; set; }
    
        public virtual SAMS_Administrator SAMS_Administrator { get; set; }
        public virtual SAMS_Administrator SAMS_Administrator1 { get; set; }
        public virtual SAMS_Department SAMS_Department { get; set; }
        public virtual SAMS_Program SAMS_Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAMS_StudentApplications> SAMS_StudentApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAMS_StudentApplications> SAMS_StudentApplications1 { get; set; }
        public virtual SAMS_UserType SAMS_UserType { get; set; }
    }
}
