//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isik.SAMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMS_StudentApplications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAMS_StudentApplications()
        {
            this.SAMS_Files = new HashSet<SAMS_Files>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string Email { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> EnrolledBy { get; set; }
        public Nullable<int> ProgramId { get; set; }
    
        public virtual SAMS_ApplicationStatus SAMS_ApplicationStatus { get; set; }
        public virtual SAMS_Department SAMS_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAMS_Files> SAMS_Files { get; set; }
        public virtual SAMS_Program SAMS_Program { get; set; }
        public virtual SAMS_Users SAMS_Users { get; set; }
        public virtual SAMS_Users SAMS_Users1 { get; set; }
    }
}
